name: Particle2Mesh CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (leave empty for CI-only run)'
        required: false
        default: ''

jobs:
  # Main build and test job
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for release notes generation
    
    - name: Debug environment
      run: |
        echo "Working directory: $(pwd)"
        echo "Repository directory: $GITHUB_WORKSPACE"
        echo "Contents of current directory:"
        ls -la
        echo "Environment variables:"
        env | sort
    
    - name: Set up environment and dependencies
      run: |
        echo "Setting up environment for dependencies"
        # Source your configuration script that sets up all paths
        if [ -f "./config.sh" ]; then
          echo "config.sh found in current directory"
          source ./config.sh
        elif [ -f "$GITHUB_WORKSPACE/config.sh" ]; then
          echo "config.sh found in GITHUB_WORKSPACE"
          source $GITHUB_WORKSPACE/config.sh
        else
          echo "ERROR: config.sh not found!"
          find $GITHUB_WORKSPACE -name "config.sh" -type f
          exit 1
        fi
        # Export variables needed by subsequent steps
        echo "DEVICE_ARCH=${DEVICE_ARCH}" >> $GITHUB_ENV
        echo "SOURCE_DIR=${SOURCE_DIR}" >> $GITHUB_ENV
        echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV
        echo "DEPENDENCY_DIR=${DEPENDENCY_DIR}" >> $GITHUB_ENV
        echo "PETSC_DIR=${PETSC_DIR}" >> $GITHUB_ENV
        echo "PETSC_ARCH=${PETSC_ARCH}" >> $GITHUB_ENV
      
    - name: Verify dependencies
      run: |
        echo "=== Verifying dependencies ==="
        echo "PETSc:"
        echo "  PETSC_DIR: $PETSC_DIR"
        echo "  PETSC_ARCH: $PETSC_ARCH"
        if [ ! -d "$PETSC_DIR" ] || [ ! -d "$PETSC_DIR/$PETSC_ARCH" ]; then
          echo "ERROR: PETSc not found at $PETSC_DIR/$PETSC_ARCH"
          exit 1
        fi
        
        echo "Kokkos:"
        KOKKOS_ROOT="$BUILD_DIR/${DEVICE_ARCH}/kokkos-meshField/install"
        echo "  KOKKOS_ROOT: $KOKKOS_ROOT"
        if [ ! -d "$KOKKOS_ROOT" ]; then
          echo "ERROR: Kokkos not found at $KOKKOS_ROOT"
          exit 1
        fi
        
        echo "Omega_h:"
        OMEGA_H_DIR="$BUILD_DIR/${DEVICE_ARCH}/omega_h-meshField/install"
        echo "  OMEGA_H_DIR: $OMEGA_H_DIR"
        if [ ! -d "$OMEGA_H_DIR" ]; then
          echo "ERROR: Omega_h not found at $OMEGA_H_DIR"
          exit 1
        fi
        
        echo "MeshFields:"
        MESHFIELDS_DIR="$BUILD_DIR/${DEVICE_ARCH}/meshField/install"
        echo "  MESHFIELDS_DIR: $MESHFIELDS_DIR"
        if [ ! -d "$MESHFIELDS_DIR" ]; then
          echo "ERROR: MeshFields not found at $MESHFIELDS_DIR"
          exit 1
        fi
        
        echo "PCMS:"
        PCMS_ROOT="$BUILD_DIR/${DEVICE_ARCH}/pcms-meshField/install"
        echo "  PCMS_ROOT: $PCMS_ROOT"
        if [ ! -d "$PCMS_ROOT" ]; then
          echo "ERROR: PCMS not found at $PCMS_ROOT"
          exit 1
        fi
        
        echo "Catch2:"
        CATCH2_ROOT="$DEPENDENCY_DIR/Catch2/install"
        echo "  CATCH2_ROOT: $CATCH2_ROOT"
        if [ ! -d "$CATCH2_ROOT" ]; then
          echo "ERROR: Catch2 not found at $CATCH2_ROOT"
          exit 1
        fi
        
        echo "Environment check complete!"
      
    - name: Build project using config.sh
      run: |
        # Use your existing config.sh script to build the project
        if [ -f "./config.sh" ]; then
          source ./config.sh
        else
          source $GITHUB_WORKSPACE/config.sh
        fi
        # Add any build commands here if they're not already in config.sh
        
    - name: Run unit tests with CTest
      run: |
        cd build
        # Source environment to ensure tests can find dependencies
        if [ -f "../config.sh" ]; then
          source ../config.sh
        else
          source $GITHUB_WORKSPACE/config.sh
        fi
        ctest --output-on-failure -V
    
    # Basic validation tests
    - name: Run validation tests
      run: |
        cd build
        if [ -f "../config.sh" ]; then
          source ../config.sh
        else
          source $GITHUB_WORKSPACE/config.sh
        fi
        
        # Run the integration test with standard parameters
        ./point2MeshMap ../create_mesh/source_mesh/source_mesh.osh ../create_mesh/target_mesh/target_mesh.osh -mat_type aijkokkos -use_gpu_aware_mpi 0
        
        # Additional validation tests could be added here
        # Example: Test with different matrix types
        # ./point2MeshMap ../create_mesh/source_mesh/source_mesh.osh ../create_mesh/target_mesh/target_mesh.osh -mat_type aij -use_gpu_aware_mpi 0
        
        # Example: Test with different mesh sizes
        # If we have different test meshes:
        # ./point2MeshMap ../create_mesh/large_source_mesh/source_mesh.osh ../create_mesh/large_target_mesh/target_mesh.osh -mat_type aijkokkos -use_gpu_aware_mpi 0
        
    - name: Collect artifacts
      if: always()
      run: |
        mkdir -p artifacts
        # Copy executable
        cp build/point2MeshMap artifacts/ || true
        # Copy test results
        cp build/Testing/Temporary/LastTest.log artifacts/ || true
        # Copy any output files
        cp build/*.vtk artifacts/ || true
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: particle2mesh-artifacts
        path: artifacts/

  # Optional deployment job - only runs when explicitly triggered
  deploy:
    needs: build-and-test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag != ''
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: particle2mesh-artifacts
        path: release-artifacts



