name: Release Deployment

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'dev'

jobs:
  build-release:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure with Release flags
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    
    - name: Build for release
      run: |
        cd build
        make -j8
    
    - name: Run validation tests
      run: |
        cd build
        ./point2MeshMapping ../create_mesh/source_mesh/source_mesh.osh ../create_mesh/target_mesh/target_mesh.osh -mat_type aijkokkos -use_gpu_aware_mpi 0
    
    - name: Package application
      run: |
        mkdir -p release_package
        cp build/point2MeshMapping release_package/
        cp README.md release_package/
        
        # Create tarball with version from tag or input
        VERSION="${{ github.ref_name }}"
        if [[ "$VERSION" != v* ]]; then
          VERSION="${{ github.event.inputs.version }}"
        fi
        
        # Remove 'v' prefix if present
        VERSION="${VERSION#v}"
        
        tar -czf particle2mesh-${VERSION}.tar.gz release_package
    
    - name: Upload release package
      uses: actions/upload-artifact@v3
      with:
        name: release-package
        path: particle2mesh-*.tar.gz
        retention-days: 30
