name: Validation and Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Static Analysis
      run: |
        # If you have static analysis tools installed (like cppcheck)
        # Run static analysis on your C++ code
        cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 *.cpp *.hpp || echo "Static analysis completed with warnings"
    
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure with Debug flags
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
    
    - name: Build for testing
      run: |
        cd build
        make -j8
    
    - name: Run integration tests
      run: |
        cd build
        # Run the executable with test meshes
        ./point2MeshMapping ../create_mesh/source_mesh/source_mesh.osh ../create_mesh/target_mesh/target_mesh.osh -mat_type aijkokkos -use_gpu_aware_mpi 0
        
    - name: Generate and upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/
        retention-days: 7